services:
  microservice_market:
    container_name: microserviceMarket
    build: ./microserviceMarket
    volumes:
      - ./microserviceMarket/code:/usr/src/app
    networks:
      - msexample
    ports:
      - "3011:3011"
    working_dir: /usr/src/app
    command: bash -c "npm install && npm run dev"
  microservice_user:
    container_name: microserviceUser
    build: ./microserviceUser
    volumes:
      - ./microserviceUser/code:/usr/src/app
    networks:
      - msexample
    ports:
      - "3012:3012"
    working_dir: /usr/src/app
    command: bash -c "npm install && npm run dev"
  gateway:
    image: node:lts
    volumes:
      - ./apigateway/code:/usr/src/app
    networks:
      - msexample
    ports:
      - "3010:3010"
    working_dir: /usr/src/app
    command: bash -c "npm install --no-audit && npm run dev"

networks:
  msexample:
    driver: bridge